---
- hosts: webserver
  become: true
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
  roles:
    - apache2
    - { role: demo_app, db_name: demo, db_user: demo, db_pass: demo }